# Generated by Django 4.1.5 on 2023-02-01 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('ST', 'standard'), ('TA', 'tandem'), ('EL', 'electric')], default='ST', max_length=2)),
                ('color', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=15)),
                ('vip_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djaunty.bike')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djaunty.renter')),
            ],
        ),
    ]
